version: '3'

services:
  jekyll:
    command: jekyll serve livereload
    image: jekyll/jekyll:4.0
    #build: $PWD/.docker/jekyll
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      -   80:4000
