version: '3'

services:
  jekyll:
    command: jekyll serve livereload
    container_name: jekyll
    # command: jekyll serve --watch --force_polling --verbose
    build: ./
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
